### ISSUE TITLE
Cannot log in to Cozytouch

### ISSUE THREAD

**Issue by VoytekD** [Cyr-ius/hass-cozytouch#24]
Custom-component installed via HACS

When trying to log in, i recive an quite vague error message, pic below.

P.S. login and password are correct... when i make a mistake, on purpose, i receive other error message.

P.S.S. My setup: Home Assistant as a virtual machine in Virtualbox.

What am I doing wrong?

<img width="314" alt="Zrzut ekranu 2020-11-30 211136" src="https://user-images.githubusercontent.com/71042707/100659846-7c8e4c00-3351-11eb-925c-299934b21647.png">

**Comment by LinoDu74** [comment]
Got exactly the same issue since months... no way to get it worked...

**Comment by Cyr-ius** [comment]
Please enable debug mode et pase the log

**Comment by ALERTua** [comment]
`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 169, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 155, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/cozytouch/config_flow.py", line 55, in async_step_user
    await async_connect(user_input)
  File "/config/custom_components/cozytouch/__init__.py", line 137, in async_connect
    return await cozytouch.get_setup()
  File "/usr/local/lib/python3.8/site-packages/cozytouchpy/client.py", line 136, in get_setup
    return SetupHandler(response_json, self)
  File "/usr/local/lib/python3.8/site-packages/cozytouchpy/handlers.py", line 44, in __init__
    self.__build_devices(data["devices"])
  File "/usr/local/lib/python3.8/site-packages/cozytouchpy/handlers.py", line 71, in __build_devices
    cozyouch_device = DevicesHandler.build(
  File "/usr/local/lib/python3.8/site-packages/cozytouchpy/handlers.py", line 201, in build
    device = CozytouchPod(data)
  File "/usr/local/lib/python3.8/site-packages/cozytouchpy/objects/device.py", line 19, in __init__
    self.states = data["states"]
KeyError: 'states'`

**Comment by alanscorp** [comment]
![image](https://user-images.githubusercontent.com/37812960/105194393-34fe9200-5b42-11eb-8e8e-6683abd81dc1.png)
![image](https://user-images.githubusercontent.com/37812960/105194450-421b8100-5b42-11eb-8cc4-f4602f2d6022.png)
![image](https://user-images.githubusercontent.com/37812960/105194758-9888bf80-5b42-11eb-92e3-33f34477ba63.png)

Logger: aiohttp.server
Source: custom_components/cozytouch/__init__.py:137
First occurred: 17:08:51 (1 occurrences)
Last logged: 17:08:51

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 169, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 155, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/cozytouch/config_flow.py", line 55, in async_step_user
    await async_connect(user_input)
  File "/config/custom_components/cozytouch/__init__.py", line 137, in async_connect
    return await cozytouch.get_setup()
  File "/usr/local/lib/python3.8/site-packages/cozytouchpy/client.py", line 136, in get_setup
    return SetupHandler(response_json, self)
  File "/usr/local/lib/python3.8/site-packages/cozytouchpy/handlers.py", line 44, in __init__
    self.__build_devices(data["devices"])
  File "/usr/local/lib/python3.8/site-packages/cozytouchpy/handlers.py", line 71, in __build_devices
    cozyouch_device = DevicesHandler.build(
  File "/usr/local/lib/python3.8/site-packages/cozytouchpy/handlers.py", line 201, in build
    device = CozytouchPod(data)
  File "/usr/local/lib/python3.8/site-packages/cozytouchpy/objects/device.py", line 19, in __init__
    self.states = data["states"]
KeyError: 'states'

**Comment by barsurfer** [comment]
@Cyr-ius I have the same issue as @ALERTua and @alanscorp with the `KeyError: 'states'`

**Comment by barsurfer** [comment]
@Cyr-ius If this helps in any way - the data object seems to be like: 
```
{
   "creationTime":1606403967000,
   "lastUpdateTime":1606403967000,
   "label":"INTERNAL (uPod/0)",
   "deviceURL":"internal://1111-1111-1111/uPod/0",
   "shortcut":false,
   "controllableName":"internal:UPodComponent",
   "definition":{
      "commands":[
         
      ],
      "states":[
         
      ],
      "dataProperties":[
         
      ],
      "widgetName":"Pod",
      "uiClass":"Pod",
      "qualifiedName":"internal:UPodComponent",
      "type":"ACTUATOR"
   },
   "available":true,
   "enabled":true,
   "placeOID":"e8272387-e0a8-417b-aa7c-cab5cd846f23",
   "widget":"Pod",
   "type":1,
   "oid":"eab924f1-7f3e-4a0a-bd4f-ebd7e5e2bfcd",
   "uiClass":"Pod"
}
```
and the appliance I have is Steatite Cube WI-FI VM 100 S4CW

**Comment by YomoShitsu** [comment]
Sorry but this integration never works for me...
But with overkiz integration it works perfectly
