### ISSUE TITLE
Error log every minute: ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by iStyles** [Cyr-ius/hass-cozytouch#35]
Getting a HA error log entry every minute.

> 2021-03-13 21:17:58 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 621, in _update_entity_states
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 282, in async_update_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 321, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 262, in state_attributes
data[ATTR_PRESET_MODE] = self.preset_mode
File "/config/custom_components/cozytouch/climate.py", line 195, in preset_mode
return COZY_TO_PRESET_MODE[preset]
KeyError: 'off'

> 2021-03-13 21:18:58 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 621, in _update_entity_states
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 282, in async_update_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 321, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 262, in state_attributes
data[ATTR_PRESET_MODE] = self.preset_mode
File "/config/custom_components/cozytouch/climate.py", line 195, in preset_mode
return COZY_TO_PRESET_MODE[preset]
KeyError: 'off'

> 2021-03-13 21:19:58 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 621, in _update_entity_states
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 282, in async_update_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 321, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 262, in state_attributes
data[ATTR_PRESET_MODE] = self.preset_mode
File "/config/custom_components/cozytouch/climate.py", line 195, in preset_mode
return COZY_TO_PRESET_MODE[preset]
KeyError: 'off'

... and it goes on...

**Comment by iStyles** [comment]
Error no longer persists after the latest reboots.
