### ISSUE TITLE
Unsupported frostprotection keyword

### ISSUE THREAD

**Issue by jugla** [Cyr-ius/hass-cozytouch#38]
This afternoon, the window has been opened and heater put themselves in a dedicated mode.
The following traceback is found:
`
2021-04-12 14:32:36 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 626, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 297, in async_update_ha_state
    self._async_write_ha_state()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 336, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/climate/__init__.py", line 266, in state_attributes
    data[ATTR_PRESET_MODE] = self.preset_mode
  File "/home/homeassistant/.homeassistant/custom_components/cozytouch/climate.py", line 195, in preset_mode
    return COZY_TO_PRESET_MODE[preset]
KeyError: 'frostprotection'
`

Here the version : 
-Home Assistant 2021.4.3
-Cozytouch 1.6.1

Running Rasperry PI4

**Comment by jugla** [comment]
seems to be related to pull request [#23](https://github.com/Cyr-ius/hass-cozytouch/pull/23)
