### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by jordangidoin** [Cyr-ius/hass-cozytouch#45]
Hello,
I would like to use your integration for my Atlantic water heater (wifi), but when I identify myself I have this error:
Unknown error occurred

**Comment by boroloko** [comment]
Hi there. I have the same problem. I have tried adding the heater via configflow and manually.
The log shows this:
Este error se originó a partir de una integración personalizada.
`Este error se originó a partir de una integración personalizada.

Logger: aiohttp.server
Source: custom_components/cozytouch/__init__.py:137
Integration: Cozytouch (documentation, issues)
First occurred: 7 de septiembre de 2021 20:53:37 (6 occurrences)
Last logged: 4:42:57

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 211, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 155, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 202, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/cozytouch/config_flow.py", line 55, in async_step_user
    await async_connect(user_input)
  File "/config/custom_components/cozytouch/__init__.py", line 137, in async_connect
    return await cozytouch.get_setup()
  File "/usr/local/lib/python3.9/site-packages/cozytouchpy/client.py", line 136, in get_setup
    return SetupHandler(response_json, self)
  File "/usr/local/lib/python3.9/site-packages/cozytouchpy/handlers.py", line 44, in __init__
    self.__build_devices(data["devices"])
  File "/usr/local/lib/python3.9/site-packages/cozytouchpy/handlers.py", line 71, in __build_devices
    cozyouch_device = DevicesHandler.build(
  File "/usr/local/lib/python3.9/site-packages/cozytouchpy/handlers.py", line 201, in build
    device = CozytouchPod(data)
  File "/usr/local/lib/python3.9/site-packages/cozytouchpy/objects/device.py", line 19, in __init__
    self.states = data["states"]
KeyError: 'states'
`
