### ISSUE TITLE
Unexpected error fetching cozytouch data: 401 since last update HA

### ISSUE THREAD

**Issue by jybi89** [Cyr-ius/hass-cozytouch#48]
Hi,

I have this problem since of last update of HA : 

`Logger: custom_components.cozytouch
Source: custom_components/cozytouch/__init__.py:92
Integration: Cozytouch (documentation, issues)
First occurred: 08:34:38 (90 occurrences)
Last logged: 10:31:05

Unexpected error fetching cozytouch data: 401
Traceback (most recent call last):
  File "/config/custom_components/cozytouch/__init__.py", line 88, in async_fecth_datas
    await cozytouch.connect()
  File "/usr/local/lib/python3.9/site-packages/cozytouchpy/client.py", line 119, in connect
    raise AuthentificationFailed(response.status)
cozytouchpy.exception.AuthentificationFailed: 401

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/cozytouch/__init__.py", line 92, in async_fecth_datas
    raise AuthentificationFailed(error) from error
cozytouchpy.exception.AuthentificationFailed: 401
`

I can't login with hass-cozytouch. I have check with app on my smartphone (Atlantic) and it's ok.

Thanks for your reponses.

**Comment by mama31** [comment]
Same issue here. I cannot connect anymore.

**Comment by iMicknl** [comment]
@jybi89 @mama31 this integration hasn't been adapted (yet) to use the new authentication method from Cozytouch. You will need to wait until a maintainer adds this.

In the mean-time you could use https://github.com/iMicknl/ha-tahoma, which supports Cozytouch as well and is targeting core (hopefully soon).

**Comment by jybi89** [comment]
> 

thanks you for your answer,

unfortunately the Overkiz integration does not allow with CozyTouch to modify the value of the climate


![image](https://user-images.githubusercontent.com/54111386/144703951-dc0a3e07-5ac2-412c-9304-bdb67383aa55.png)


`type: custom:simple-thermostat
style: |
  ha-card {
    --st-font-size-xl: 24px;
    --st-font-size-m: 10px;
    --st-font-size-title: 10px;
    --st-font-size-sensors: 15px;
    --st-spacing: 1px;
  }
entity: climate.zone_1_3
name: false
icon: false
control:
  preset:
    away: true
    none:
      name: Not set
  hvac: true
layout:
  mode:
    names: true
    icons: true
    headings: false
header: false
`

**Comment by iMicknl** [comment]
@jybi89 you can report issues for the Overkiz integration [here](https://github.com/iMicknl/ha-tahoma).
