### ISSUE TITLE
Zonecontrol 2.0 integration problem

### ISSUE THREAD

**Issue by newbie31fr** [Cyr-ius/hass-cozytouch#52]
My cozytouch is connected & configured with zonecontrol 2.0 ( shogun) from atlantic ( heat/cooling equipment with multiple room control). 
https://www.atlantic.fr/La-marque/Nos-anciens-produits/Climatisation/Systeme-Zone-Control-2.0

The control zone 2.0 is connected wit last cozytouch box with wifi link.
With android app, i can look temperature and pilot A/C of each zone. 

Here we are on HASS integraton.  cozytouch plugin is installed and connected to account but I have access to temperature sensors of each room but not able to pilot  cooling/heater 

It appears that i have 2 errors on HASS log.   
Any help to be able to control this equipment on HASS ? 

--------------------------------------
Logger: cozytouchpy.handlers
Source: /usr/local/lib/python3.9/site-packages/cozytouchpy/handlers.py:79
First occurred: 20:59:58 (4 occurrences)
Last logged: 21:24:15

Error building device, skipping: Unknown device Wifi
Error building device, skipping: Unknown device AtlanticPassAPCZoneControl
---------------------------------------

Logger: homeassistant.components.climate
Source: custom_components/cozytouch/climate.py:82
Integration: Thermostat (documentation, issues)
First occurred: 20:59:58 (2 occurrences)
Last logged: 21:24:15

Error while setting up cozytouch platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/cozytouch/climate.py", line 45, in async_setup_entry
    CozytouchStandaloneThermostat(device, coordinator, ThermalState.HEAT)
  File "/config/custom_components/cozytouch/climate.py", line 71, in __init__
    self.__load_features()
  File "/config/custom_components/cozytouch/climate.py", line 82, in __load_features
    self.climate.is_state_supported(DeviceState.PASS_APC_HEATING_MODE_STATE)
  File "/usr/local/lib/python3.9/site-packages/cozytouchpy/objects/climate.py", line 116, in is_state_supported
    return state in self.supported_states
  File "/usr/local/lib/python3.9/site-packages/cozytouchpy/objects/climate.py", line 110, in supported_states
    sensor_states = [state["name"] for state in sensor.states]
AttributeError: 'str' object has no attribute 'states'
---------------------------------------------

**Comment by newbie31fr** [comment]
> You can try https://github.com/iMicknl/ha-tahoma#installation for now. Eventually this will be supported in the Overkiz integration (part of core).

I have also try before posting issue. 
Overkiz intégration is Aldo correctes installés in my hass configuration. Control zone is "correctly" detected but unfornetly i Can only see température and not pilot the equipment. So no more functionality
